config/routes.rb
Rails.application.routes.draw do

    ##static home page
    root 'static_pages#home'

    get '/help', to: 'static_pages#help'

    delete '/delete', to:'watchlists#destroy'

    # post '/user_picks', to: 'static_pages#home'
    post '/user_picks', to: 'users#show'

    ##create a new user
    resources :users

    ##manage stocks in db
    resources :stocks

    ##add new stocks to watchlists
    resources :watchlists, only: [:new, :create, :destroy]

    ##add new quotes
    resources :historical_quotes, only: [:new, :create, :destroy, :show]

    ##create new games
    resources :games

    ##new game



    ##login routes
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @quotes = daily_quote
    @user_picks = user_list(params["stock"])
  end



  def help
  end

  def about
  end

  def contact

  end

end

app/views/static_pages/home.html.erb
<div class="center jumbotron">
   <h1 id="home-header">StockFights</h1>
   <h3>
      Track Historical and Current Stock Data. Create Watchlists. Make your daily picks and compete with the developer for bragging rights!
   </h3>
   <p>
      <% if logged_in? %>
   <p align='center' id="welcome">Welcome, <%= current_user.first_name %></p>
   <%= link_to "Current Watchlist", user_path(current_user), class: "btn btn-lg btn-primary" %>
   <% else %>
   <%= link_to "Sign up now!", new_user_path, class: "btn btn-lg btn-primary" %>
   <% end %>
   </p>
</div>
<br>



<h3>StockFathers's picks:</h3>
<div class="master-picks-box">
 <ul>
      <% @quotes.each do |quote|  %>
      <li>
        <p><%= link_to quote["1. symbol"], stock_path(quote["1. symbol"]) %></p> Last:
        <%= quote["2. price"] %>
      </li>
    <% end %>
 </ul>
</div>