config/routes.rb
Rails.application.routes.draw do

    ##static home page
    root 'static_pages#home'

    get '/help', to: 'static_pages#help'

    delete '/delete', to:'watchlists#destroy'

    # post '/user_picks', to: 'static_pages#home'
    post '/user_picks', to: 'users#show'

    ##create a new user
    resources :users

    ##manage stocks in db
    resources :stocks

    ##add new stocks to watchlists
    resources :watchlists, only: [:new, :create, :destroy]

    ##add new quotes
    resources :historical_quotes, only: [:new, :create, :destroy, :show]

    ##create new games
    resources :games

    ##new game



    ##login routes
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'



end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token

  has_many :watchlists
  has_many :games
  has_many :stocks, through: :watchlists


  before_save { email.downcase! }
  validates :first_name, :last_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, :presence => true, length: { minimum: 6 }



                    
                    
                    
  ##Returns a hash digest part of the string 
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  ##Returns a random token 
  def User.new_token 
    SecureRandom.urlsafe_base64
  end 

  #Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget 
    update_attribute(:remember_digest, nil)
  end 

  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the StockFights!"
      redirect_to root_path
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end


##find by or create
##update attributes
##iterate through user picks and update information with update attributes
  def show
    @user = User.find_by(:id => params[:id])
    add_single_stock(params["stock"])
    @user_picks = user_list(params["stock"])
    if @user_picks
      @user_picks.each do |stock|
        stock_to_update = Stock.find_by(:symbol => params["stock"])
        stock_to_update.update_attributes(:last => stock["2. price"],
                                          :volume => stock["3. volume"])
    end
  else
      render :show
   end
  end

  def edit 
    @user = User.find(params[:id])
  end 

  def update 
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] == "Profile Updated"
      redirect_to @user     
    else 
      @errors = @user.errors.full_messages
      render :edit
    end 
  end 

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.last_name, class: "gravatar")
  end

end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/errors', object: @user %>

        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: 'form-control' %>

        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.submit "Submit Changes", class: "btn btn-primary" %>

    <% end %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h2>
  Sign Up for StockFights!
</h2>

<div align="center" class="errors">
  <%= render 'shared/errors', locals: {errors: @errors} if @errors %>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit "Create my account", class: "button btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if @user %>
  <div align="right" class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1>
          <%= gravatar_for @user %>
          <%= current_user.first_name %>'s Current Watchlist
        </h1>
      </section>
    </aside>
  </div>
<% end %>



  
<h1 id="watchlist-header">Currently Watching:</h1>
<div class="col-md-2 col-md-offset-0">
   <form id="quick-quote" action="/user_picks" method="POST">
      <label for="stock">Quick Quotes:</label>
      <input type="text" name="stock">
      <input name="authenticity_token" type="hidden"
         value="x37DrAAwyIIb7s+w2+AdoCR8cAJIpQhIetKRrPgG5VA=">
      <input type="submit" value="Get Quote", class=" button btn btn-primary"><br><br>
      <strong>Add exactly three stocks to your watchlist to play the game ~~~~></strong>
   </form>
   <footer>There is no limit on how many stocks can be in a watchlist at one time. However, exactly three are required     to start a new game</footer>
</div>




<div class="user_picks-box">
 <ul>
  <% if @user_picks %>
      <% @user_picks.each do |quote|  %>
      <li>
        <p><%= link_to quote["1. symbol"], stock_path(quote["1. symbol"]) %></p> Last:
          <%= quote["2. price"] %><br>
          <%= button_to "Add to Watchlist", "/watchlists", method: "POST", params: { :symbol => "#{quote["1. symbol"]}", :last => quote["2. price"]  }, class: "btn-primary btn-xs"%>
          <%= link_to "Back to Watchlist", user_path(current_user), align: "middle", class: "btn-primary btn-xs back-watchlist"  %>
      </li>
    <% end %>
  <% end %>
 </ul>
</div>

create way to add all quick quotes to watchlists


<% if @user %>
  <div class="master-picks-box">
    <ul>
      <% @user.watchlists.each do |watchlist| %>
      <li>
        <%= link_to watchlist.stock.symbol, stock_path(watchlist.stock.symbol) %><br>
        <strong>Last:</strong> <%= watchlist.stock.last %><br>
        <strong>Volume:</strong> <%= watchlist.stock.volume %><br>
        <%= link_to "Delete", watchlist_path(watchlist.id), method: :delete, class: "btn-primary btn-xs" %>
      </li>
      <% end %>
    </ul>
  </div>
<% end %>

     <% if @user && @user.watchlists.count == 3 %>
       <p><%= button_to 'Start Game!', '/games' , method: "POST", class: "btn btn-lg btn-link", params: {:stock => @user.watchlists.first(3)} %></p>
    <% end %>