config/routes.rb
Rails.application.routes.draw do

    ##static home page
    root 'static_pages#home'

    get '/help', to: 'static_pages#help'

    delete '/delete', to:'watchlists#destroy'

    # post '/user_picks', to: 'static_pages#home'
    post '/user_picks', to: 'users#show'

    ##create a new user
    resources :users

    ##manage stocks in db
    resources :stocks

    ##add new stocks to watchlists
    resources :watchlists, only: [:new, :create, :destroy]

    ##add new quotes
    resources :historical_quotes, only: [:new, :create, :destroy, :show]

    ##create new games
    resources :games

    ##new game



    ##login routes
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'



end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
       <a href="#">StockFights</a>
    by <a href="http://www.linkedin/in/mitchmele">Mitch Mele</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", "#" %></li>
      <li><%= link_to "Home", root_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "StockFights", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", "#" %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataFights</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Krona+One" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
        <%= yield %>
    </div>
      <div id="main-footer"><%= render 'layouts/footer' %></div>
  </body>
</html>